[build-system]
requires = [
    "setuptools>=40.8.0",
    "wheel",
    'uiucprescon.build @ git+https://github.com/UIUCLibrary/uiucprescon_build.git@v0.1.2',
    "conan>=1.50.0,<2.0"
]
build-backend = "uiucprescon.build"

[tool.cibuildwheel]
test-requires = [
    "pytest",
]
test-command = [
    "pytest {package}/tests"
]
build-frontend = "build"
skip = [
    "cp36-*",
    "cp37-macosx_*",
    "pp*",
    "*-win32",
    "*-musllinux*",
    "*-manylinux_i686"
]
environment-pass = ["CONAN_COMPILER_LIBCXX", "CONAN_COMPILER_VERSION", "CONAN_USER_HOME"]

[tool.cibuildwheel.macos]

before-all = [
    "python3 -m venv /tmp/ciwheelbuilder/py3exiv2bind/venv",
    "/tmp/ciwheelbuilder/py3exiv2bind/venv/bin/python -m pip install wheel",
    "/tmp/ciwheelbuilder/py3exiv2bind/venv/bin/python -m pip install -r requirements/requirements_conan.txt cmake",
    "/tmp/ciwheelbuilder/py3exiv2bind/venv/bin/conan profile new $ENVTMPDIR/.conan/profiles/default --detect --force",
    "if [ -z \"$CONAN_COMPILER_VERSION\" ]; then : ; else /tmp/ciwheelbuilder/py3exiv2bind/venv/bin/conan profile update settings.compiler.version=$CONAN_COMPILER_VERSION default; fi",
    ". /tmp/ciwheelbuilder/py3exiv2bind/venv/bin/activate && conan install ./ --build missing --install-folder=$CONAN_BUILD_INFO_DIR"
]
[tool.cibuildwheel.macos.environment]
ENVTMPDIR="/tmp/ciwheelbuilder/py3exiv2bind"
CONAN_USER_HOME="/tmp/ciwheelbuilder/py3exiv2bind"
CONAN_DEFAULT_PROFILE_PATH="/tmp/ciwheelbuilder/py3exiv2bind/.conan/profiles/default"
CONAN_BUILD_INFO_DIR="/tmp/ciwheelbuilder/py3exiv2bind/build/"

[tool.cibuildwheel.windows]
before-all = [
    "pip install wheel",
    "pip install -r requirements/requirements_conan.txt cmake ninja",
    "conan profile new default --detect --force",
    "conan profile update settings.compiler.version=%CONAN_COMPILER_VERSION% default",
    "conan install ./ --build missing",
]
[tool.cibuildwheel.windows.environment]
CONAN_USER_HOME="$TEMP/conan"

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux2014"
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel}"
before-all = [
    "cc --version", "cc -dumpfullversion -dumpversion",
    "pip3 install -r requirements/requirements_conan.txt cmake ninja",
    "conan profile new /tmp/ciwheelbuilder/py3exiv2bind/.conan/profiles/default --detect",
    "if [ -z \"$CONAN_COMPILER_LIBCXX\" ]; then : ; else conan profile update settings.compiler.libcxx=$CONAN_COMPILER_LIBCXX default; fi",
    "if [ -z \"$CONAN_COMPILER_VERSION\" ]; then : ; else conan profile update settings.compiler.version=$CONAN_COMPILER_VERSION default; fi",
    "conan profile show default",
    "conan install ./ --build missing",

]
[tool.cibuildwheel.linux.environment]
CONAN_USER_HOME="/tmp/ciwheelbuilder/py3exiv2bind"
CONAN_DEFAULT_PROFILE_PATH="/tmp/ciwheelbuilder/py3exiv2bind/.conan/profiles/default"
CONAN_BUILD_INFO_DIR="/tmp/ciwheelbuilder/py3exiv2bind/build/"
PYTHONFAULTHANDLER="True"
#
