[build-system]
requires = ["setuptools>=40.8.0", "wheel", "cmake", "ninja", "conan","pybind11", 'macholib; platform_system == "Darwin"']
#build-backend = "setuptools.build_meta"
build-backend = "local_backend"
backend-path = ["builders"]


[tool.cibuildwheel]
test-requires = [
    "pytest",
]
test-command = [
    "pytest {package}/tests"
]
build-frontend = "build"
skip = ["*-win32", "*-manylinux_i686", "*-musllinux_i686"]

[tool.cibuildwheel.windows]
before-all = [
    "pip install conan",
    "conan install {project} --build --no-import"
]

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux2014"