from typing import Dict, List

class Exiv2AnyError(Exception): ...

class Image:
    def __init__(self, arg0: str) -> None: ...
    def get_icc_profile_data(self) -> bytes: ...
    def is_good(self) -> bool: ...
    @property
    def error_logs(self) -> List[str]: ...
    @property
    def exif(self) -> Dict[str,str]: ...
    @property
    def filename(self) -> str: ...
    @property
    def iptc(self) -> Dict[str,str]: ...
    @property
    def pixelHeight(self) -> int: ...
    @property
    def pixelWidth(self) -> int: ...
    @property
    def warnings_logs(self) -> List[str]: ...
    @property
    def xmp(self) -> Dict[str,str]: ...

class NoICCError(Exception): ...

def exiv2_version() -> str: ...
def set_dpi(image: str, x: int, y: int) -> None: ...
